### ISSUE TITLE
水印可以被隐藏

### ISSUE THREAD

**Issue by icepole-jon** [loadchange/gwm#11]
生成的水印都带有一个id，虽然不能在元素本身上修改样式，但因为这个id，就可以另外写样式
![](https://s2.ax1x.com/2019/06/25/ZZAfqf.png)

**Comment by maqingbo** [comment]
> 生成的水印都带有一个id，虽然不能在元素本身上修改样式，但因为这个id，就可以另外写样式
> ![](https://camo.githubusercontent.com/df2ed846ee7e7ce6d1eef91444f797ab7fe3ad8a/68747470733a2f2f73322e617831782e636f6d2f323031392f30362f32352f5a5a416671662e706e67)

找到一种解决办法，gwm 初始化时填写 css 参数：

```js
gwm.creation({
  'css': {
    'display': 'block',
    'visibility': 'visible',
    'opacity': 1,
    'clip-path': 'none',
    'transform': 'translateX(0)'
  }
})
```
作者在`lib > helpers > bindCSS.ts`文件中使用 js 方法把参数中的这些 css 属性转化成行内样式，在控制台新增加的属性属于外联样式，不能覆盖行内样式，算是间接解决了这个问题。

弊端是需要考虑到所有可以隐藏元素的 css 方法，上面代码里是我能想到的方法，如果你还能想到其他的，请在评论里告诉我！

**Comment by icepole-jon** [comment]
@maqingbo 我直接改了 creator.ts 注释掉id的设置（73行），然后重新编译使用 :)

**Comment by maqingbo** [comment]
@icepole-jon 如此简单粗暴....怎么维护啊😂

**Comment by loadchange** [comment]
> @maqingbo 我直接改了 creator.ts 注释掉id的设置（73行），然后重新编译使用 :)

去id是没用的，比如 `body > div:first-child` 怎么样都能被选择到，我觉得 @maqingbo  方案可行，把会破坏显示的属性都加在行内，我在库上加一下吧
