### ISSUE TITLE
style.setProperty 不能设置 pointerEvents 和 zIndex

### ISSUE THREAD

**Issue by icepole-jon** [loadchange/gwm#15]
bindCss.ts 中的 isSupport 用 document.documentElement.style 来判断属性是否可用，但里面的key是驼峰的形式，然后元素设置样式的时候，elem.style.setProperty(key, css[key], 'important') setProperty 的key不支持驼峰形式，必须是横杠的，导致pointerEvents和zIndex没有设置上。

**Comment by chenanchina** [comment]
{
  css: {'z-index': 99}

}
