### ISSUE TITLE
container参数无效

### ISSUE THREAD

**Issue by ZG4vin** [loadchange/gwm#4]
传入了一个id为div1 的div容器，为啥填充的还是整个页面都有水印?

**Comment by loadchange** [comment]
这个参数需要接受一个DOM节点对象，看来传入string也是有必要支持的，我一会发一下

**Comment by ZG4vin** [comment]
我是这样传入的：
container:document.getElementById('div1')
在Demo中发现也不能局部加水印

**Comment by ZG4vin** [comment]
ok了 多谢修改
