### ISSUE TITLE
怎么解决打印网页空白问题呢

### ISSUE THREAD

**Issue by fiveLucky** [loadchange/gwm#9]
当前的这些水印方案，都是插入一个背景图片为水印的div元素，遮罩在整个页面上面，虽说解决了水印需求，但是对于网页打印就完全无解了啊，大佬有没有什么思路

**Comment by loadchange** [comment]
用 `element` 模式吧

**Comment by mzcc666GtHb** [comment]
在vue 项目中 element模式也不行为什么
